spring:
  application:
    name: car-management
  datasource:
    url: jdbc:h2:mem:car_management_db
    username:
    password:

h2:
  console:
    enabled: true
    path: /h2-console
    settings:
      trace: false
      web-allow-others: false